Use a Map which was only added to JavaScript in es2015
src/index.ts(6,16): error TS2583: Cannot find name 'Map'. Do you need to
change your target library? Try changing the 'lib' compiler option to
'es2015' or later.